AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: stripe-app

Globals:
  Function:
    Timeout: 3
    MemorySize: 128

Resources:
  StripePaymentFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Events:
        StripePaymentApi:
          Type: Api
          Properties:
            Path: /create-payment-intent
            Method: get
